AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates the IAM service role used by AWS Backup. It should be
  deployed to each AWS Organizations member account. #magic___^_^___line
Parameters:
  pCrossAccountBackupRoleName:
    Type: String
    Description: This is the IAM role name for the cross-account backup role that
      carries out the backup activities.
    Default: AWSBackupSolutionRole
  pCrossAccountConfigRoleName:
    Type: String
    Description: This is the IAM role name for the config role that allow AWS config
      record the backup activities.
    Default: AWSConfigSolutionRole
  DeployConfigurationRecorder:
    Description: 'Do you want to configure a Configuration Recorders for each region
      you use?'
    Type: String

  # Parameters for tagging
  CommitId:
    Description: The commit id for the change
    Type: String
  BusinessUnit:
    Description: Business Unit Name
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
    - Marketing
    - Engineering
    - R&D
    ConstraintDescription: Must be a valid business unit
    Default: Engineering
  CostCenter:
    Description: Cost Center for AWS Services
    Type: String
    MinLength: '1'
    MaxLength: '255'
    Default: '00000'
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
    - Development
    - QA
    - Production
    ConstraintDescription: Must be a valid environment.
    Default: Development
  ApplicationOwner:
    Description: Email address of application owner
    Type: String
    Default: selfserviceservicecatalog@example.com
  Application:
    Description: Application Name
    Type: String
    Default: Example Application

Conditions:
  DeployConfigurationRecorderCondition: !Equals [ !Ref DeployConfigurationRecorder, "true" ]

Resources:
  rOrgAccountBackupRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref pCrossAccountBackupRoleName
      Description: Allows AWS Backup to access AWS services
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - backup.amazonaws.com
          Action:
          - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
      - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores
      Tags:
      - Key: Application
        Value: !Ref Application
      - Key: CommitId
        Value: !Ref CommitId
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: CostCenter
        Value: !Ref CostCenter
      - Key: Environment
        Value: !Ref Environment
      - Key: ApplicationOwner
        Value: !Ref ApplicationOwner

  rOrgAccountConfigRole:
    Condition: DeployConfigurationRecorderCondition
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref pCrossAccountConfigRoleName
      Description: Allows AWS Config to access AWS services
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - config.amazonaws.com
          Action:
          - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole
      Tags:
      - Key: Application
        Value: !Ref Application
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: CostCenter
        Value: !Ref CostCenter
      - Key: Environment
        Value: !Ref Environment
      - Key: ApplicationOwner
        Value: !Ref ApplicationOwner
Outputs:
  oOrgAccountBackupRoleName:
    Value: !Ref pCrossAccountBackupRoleName
  rOrgAccountConfigRoleName:
    Value: !Ref pCrossAccountConfigRoleName
