AWSTemplateFormatVersion: '2010-09-09'
Description: Backup & Recovery with AWS Backup Restore Testing Plan

Parameters:
  RestoreTestSchedule:
    Description: The CRON job to initiate restore test plan. For example, cron(0 7 ? * 6 *) weekly on Saturday, at 07:00 UTC.
    Type: String
    Default: cron(0 7 ? * 6 *)
  RestoreTestingVaultName:
    Description: The restore testing vault name.
    Type: String
    Default: AWSBackupSolutionCentralVault
  RestoreSubnetEC2:
    Description: The restore subnet for EC2 restore testing.
    Type: String
  RestoreSecurityGroupIdEC2:
    Description: The restore security group IDs for EC2 restore testing.
    Type: String
  RestoreValidationHoursEC2:
    Description: The number of hours to keep the EC2 instance active for restore validation.
    Type: String
    Default: 6
  SelectionWindowDays:
    Description: The number of days to select recovery points.
    Type: String
    Default: 365
  StartWindowHours:
    Description: The number of hours for the restore testing start window.
    Type: String
    Default: 24
  TagKey:
    Description: The tag key used for selecting resources. For example, "backup".
    Type: String
    Default: "backup"
  TagValue:
    Description: The tag value used for selecting resources. For example, "daily".
    Type: String
    Default: "daily"

  # Parameters for tagging
  CommitId:
    Description: The commit id for the change
    Type: String
  BusinessUnit:
    Description: Business Unit Name.
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
      - Marketing
      - Engineering
      - R&D
    Default: Engineering
  CostCenter:
    Description: Cost Center for AWS Services.
    Type: String
    MinLength: '1'
    MaxLength: '255'
    Default: '00000'
  Environment:
    Description: Environment.
    Type: String
    AllowedValues:
      - Development
      - QA
      - Production
    Default: Development
  ApplicationOwner:
    Description: Email address of the application owner.
    Type: String
    Default: someone@example.com
  Application:
    Description: Application Name.
    Type: String
    Default: Backup and Recovery with AWS Backup

Resources:
  AWSBackupRestoreTestingRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: Allows AWS Backup to access AWS services for restore testing.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - restore-testing.backup.amazonaws.com
                - backup.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      # IMPORTANT - UPDATE PERMISSIONS TO ALIGN TO YOUR RESTORE TESTING
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
      Policies:
        - PolicyName: "RestoreTestingPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: BackupActions
                Effect: Allow
                Action:
                  - backup:DescribeRecoveryPoint
                  - backup:DescribeRestoreJob
                  - backup:DescribeProtectedResource
                  - backup:GetRecoveryPointRestoreMetadata
                  - backup:ListBackupVaults
                  - backup:ListProtectedResources
                  - backup:ListRecoveryPointsByBackupVault
                  - backup:StartRestoreJob
                Resource: "*"
              - Sid: IamPassRole
                Effect: Allow
                Action: iam:PassRole
                Resource: "*"
                Condition:
                  StringEquals:
                    iam:PassedToService: backup.amazonaws.com
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: CommitId
          Value: !Ref CommitId
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: ApplicationOwner
          Value: !Ref ApplicationOwner

  RestoreTestPlan:
    Type: AWS::Backup::RestoreTestingPlan
    Properties:
      RecoveryPointSelection:
        Algorithm: LATEST_WITHIN_WINDOW
        IncludeVaults:
          - !Sub "arn:aws:backup:${AWS::Region}:${AWS::AccountId}:backup-vault:${RestoreTestingVaultName}"
        RecoveryPointTypes:
          - CONTINUOUS
          - SNAPSHOT
        SelectionWindowDays: !Ref SelectionWindowDays
      RestoreTestingPlanName: aws_backup_organization_restore_test_plan
      ScheduleExpression: !Ref RestoreTestSchedule
      ScheduleExpressionTimezone: UTC
      ScheduleStatus: ACTIVE
      StartWindowHours: !Ref StartWindowHours
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: CommitId
          Value: !Ref CommitId
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: ApplicationOwner
          Value: !Ref ApplicationOwner

  RestoreTestSelection:
    Type: AWS::Backup::RestoreTestingSelection
    Properties:
      IamRoleArn: !GetAtt AWSBackupRestoreTestingRole.Arn
      ProtectedResourceArns:
        - "*"
      ProtectedResourceConditions:
        StringEquals:
          - Key: !Sub "aws:ResourceTag/${TagKey}"
            Value: !Ref TagValue
      ProtectedResourceType: EC2
      RestoreMetadataOverrides:
        subnetId: !Ref RestoreSubnetEC2
        securityGroupIds: !Join [ "", ["[\"", !Ref RestoreSecurityGroupIdEC2, "\"]"] ]
      RestoreTestingPlanName: !Ref RestoreTestPlan
      RestoreTestingSelectionName: aws_backup_organization_restore_test_selection
      ValidationWindowHours: !Ref RestoreValidationHoursEC2

Outputs:
  RestoreTestingPlanArn:
    Description: ARN of the Restore Testing Plan
    Value: !Ref RestoreTestPlan
    Export:
      Name: RestoreTestingPlanArn
