version: 0.2
phases:
  install:
    commands:
#      - apt-get -y update
      - gem install cfn-nag      
  build:
    commands:
      - chmod +x codebuild/ValidateTemplates/run-cfnnag.sh
      - /bin/bash codebuild/ValidateTemplates/run-cfnnag.sh
