Description: "StackSet for Backup and Recovery with AWS Backup Member Account Resources"
Parameters:
  StackSetName:
    Description: Name of the stackset
    Type: String
    Default: "organizations-aws-backup-member-accounts"

  StackSetS3BucketName:
    Description: Name of S3 bucket where stackset templates are stored.
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/bucket"

  StackSetTemplate:
    Description: Name of stackset template
    Type: String
    Default: "deployment/cloudformation/stacks/aws-backup-member-account.yaml"

  StackSetDescription:
    Description: Description for StackSet
    Type: String
    Default: "StackSet for Backup and Recovery with AWS Backup Member Account Resources"

  StackSetTargetOUsParameterStore:
    Description: Target organization unit ids
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Default: "/backup/target/organizational-units"

  StackSetTargetRegionsParameterStore:
    Description: Target regions
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Default: "/backup/target/regions"

  # Parameters for stack
  CentralBackupVaultArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: This is the account number for the account that is used to house centralized backups from member accounts
    Default: "/backup/central-vault-arn"
  CentralAccountId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: The AWS Account ID for the central account that will be the secondary store for all AWS Backups.  Secondary copies and restore testing will be in this account.
    Default: "/backup/central-account-id"

  # Parameters for tagging
  CommitId:
    Description: The commit id for the change
    Type: String
  BusinessUnit:
    Description: Business Unit Name
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
    - Marketing
    - Engineering
    - R&D
    ConstraintDescription: Must be a valid business unit
    Default: Engineering
  CostCenter:
    Description: Cost Center for AWS Services
    Type: String
    MinLength: '1'
    MaxLength: '255'
    Default: '00000'
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
    - Development
    - QA
    - Production
    ConstraintDescription: Must be a valid environment.
    Default: Development
  ApplicationOwner:
    Description: Email address of application owner
    Type: String
    Default: selfserviceservicecatalog@example.com
  Application:
    Description: Application Name
    Type: String
    Default: Example Application

Resources:
  StackSetDeployment:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Ref StackSetName
      #      TemplateBody: String
      TemplateURL: !Sub "https://s3.amazonaws.com/${StackSetS3BucketName}/${StackSetTemplate}"
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      CallAs: DELEGATED_ADMIN
      Capabilities:
      - CAPABILITY_NAMED_IAM
      Description: !Ref StackSetDescription
      OperationPreferences:
        FailureToleranceCount: 0
        #        FailureTolerancePercentage: Integer
        MaxConcurrentCount: 1
        #        MaxConcurrentPercentage: Integer
        RegionConcurrencyType: SEQUENTIAL
        #        RegionOrder:
        #          - String
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
      - DeploymentTargets:
          #            Accounts: !Ref StackSetTargetAccounts
          OrganizationalUnitIds: !Ref StackSetTargetOUsParameterStore
          #          ParameterOverrides:
          #            - Parameter
        Regions: !Ref StackSetTargetRegionsParameterStore
      Parameters:
      - ParameterKey: CommitId
        ParameterValue: !Ref CommitId
      - ParameterKey: CentralBackupVaultArn
        ParameterValue: !Ref CentralBackupVaultArn
      - ParameterKey: CentralAccountId
        ParameterValue: !Ref CentralAccountId
      - ParameterKey: Application
        ParameterValue: !Ref Application
      - ParameterKey: BusinessUnit
        ParameterValue: !Ref BusinessUnit
      - ParameterKey: CostCenter
        ParameterValue: !Ref CostCenter
      - ParameterKey: Environment
        ParameterValue: !Ref Environment
      - ParameterKey: ApplicationOwner
        ParameterValue: !Ref ApplicationOwner

      Tags:
      - Key: Application
        Value: !Ref Application
      - Key: CommitId
        Value: !Ref CommitId
      - Key: BusinessUnit
        Value: !Ref BusinessUnit
      - Key: CostCenter
        Value: !Ref CostCenter
      - Key: Environment
        Value: !Ref Environment
      - Key: ApplicationOwner
        Value: !Ref ApplicationOwner
