Description: "StackSet for Backup and Recovery with AWS Backup Restore Test Plan"
Parameters:
# parameters for stackset
  StackSetName:
    Description: Name of the stackset
    Type: String
    Default: organizations-aws-backup-central-backup-account
  StackSetS3BucketName:
    Description: Name of S3 bucket where stackset templates are stored.
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/bucket"
  StackSetTemplate:
    Description: Name of stackset template
    Type: String
    Default: "deployment/cloudformation/stacks/aws-backup-central-backup-account.yaml"
  StackSetDescription:
    Description: Description for StackSet
    Type: String
    Default:  "StackSet for Backup and Recovery with AWS Backup Central Acct Resources"
  StackSetCentralAccountOUParameterStore:
    Description: Target organization unit ids
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/central-account-ou"
  StackSetCentralBackupAccountIdParameterStore:
    Description: Central backup and restore account id
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/central-account-id"
  StackSetCentralBackupAccountRegionParameterStore:
    Description: Central backup and restore account region
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/central-account-region"

  # Parameters for stack
  StackSetOrgIdParameterStore:
    Description: The AWS Organization ID for the solution
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/backup/org-id"

# Parameters for tagging
  CommitId:
    Description: The commit id for the change
    Type: String
  BusinessUnit:
    Description: Business Unit Name
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
      - Marketing
      - Engineering
      - R&D
    ConstraintDescription: Must be a valid business unit
    Default:  Engineering
  CostCenter:
    Description: Cost Center for AWS Services
    Type: String
    MinLength: '1'
    MaxLength: '255'
    Default:  '00000'
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
      - Development
      - QA
      - Production
    ConstraintDescription: Must be a valid environment.
    Default:  Development
  ApplicationOwner:
    Description: Email address of application owner
    Type: String
    Default:  selfserviceservicecatalog@example.com
  Application:
    Description: Application Name
    Type: String
    Default:  Example Application


Resources:
  StackSetDeployment:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Ref StackSetName
#      TemplateBody: String
      TemplateURL: !Sub "https://s3.amazonaws.com/${StackSetS3BucketName}/${StackSetTemplate}"
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      CallAs: DELEGATED_ADMIN
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: !Ref StackSetDescription
      OperationPreferences:
        FailureToleranceCount: 0
#        FailureTolerancePercentage: Integer
        MaxConcurrentCount: 1
#        MaxConcurrentPercentage: Integer
        RegionConcurrencyType: SEQUENTIAL
#        RegionOrder:
#          - String
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        -
          DeploymentTargets:
            Accounts:
              - !Ref StackSetCentralBackupAccountIdParameterStore
            AccountFilterType: INTERSECTION
            OrganizationalUnitIds:
              - !Ref StackSetCentralAccountOUParameterStore
          #          ParameterOverrides:
          #            - Parameter
          Regions:
            - !Ref StackSetCentralBackupAccountRegionParameterStore
      Parameters:
        -
          ParameterKey: pOrganizationId
          ParameterValue: !Ref StackSetOrgIdParameterStore
        - ParameterKey: Application
          ParameterValue: !Ref Application
        - ParameterKey: CommitId
          ParameterValue: !Ref CommitId
        - ParameterKey: BusinessUnit
          ParameterValue: !Ref BusinessUnit
        - ParameterKey: CostCenter
          ParameterValue: !Ref CostCenter
        - ParameterKey: Environment
          ParameterValue: !Ref Environment
        - ParameterKey: ApplicationOwner
          ParameterValue: !Ref ApplicationOwner
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: BusinessUnit
          Value: !Ref BusinessUnit
        - Key: CommitId
          Value: !Ref CommitId
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: ApplicationOwner
          Value: !Ref ApplicationOwner

